/*
 * Copyright 2020 Frederic Rible <f1oat@f1oat.org>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.f1oat.launchpad.x.gateway;

import javax.sound.midi.MidiDevice;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author f1oat
 */
public class GUI extends javax.swing.JFrame implements iNotifier {

    MidiHandler myMidi = new MidiHandler();
    
    public void setPadColor(int index, int r, int g, int b) {
        this.jPanelKeyboard.setPadColor(index, r, g, b);
    }
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        myMidi.setGUI(this);
        System.out.println("Java version " + System.getProperty("java.version"));

        jComboBox_FL_in.getModel().setSelectedItem("FL_to_LPX");
        jComboBox_FL_out.getModel().setSelectedItem("LPX_to_FL");
        jComboBox_FL_out_native.getModel().setSelectedItem("LPX_to_FL (Native)");
        jComboBox_LPX_in.getModel().setSelectedItem("MIDIIN2 (LPX MIDI)");
        jComboBox_LPX_out.getModel().setSelectedItem("LPX MIDI");
            
        configure();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMode = new javax.swing.ButtonGroup();
        jComboBox_FL_in = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_FL_out = new javax.swing.JComboBox<>();
        jButtonApply = new javax.swing.JButton();
        jToggleButtonRun = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelKeyboard = new com.f1oat.launchpad.x.gateway.jPanelKeyboard();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_LPX_in = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_LPX_out = new javax.swing.JComboBox<>();
        jRadioButtonModeProg = new javax.swing.JRadioButton();
        jRadioButtonModeNative = new javax.swing.JRadioButton();
        jComboBox_FL_out_native = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 450));

        jComboBox_FL_in.setModel(new midiComboBoxModel(false));

        jLabel1.setText("IN from FL-Studio");

        jLabel2.setText("OUT to FL-Studio");

        jComboBox_FL_out.setModel(new midiComboBoxModel(true));

        jButtonApply.setText("Apply");
        jButtonApply.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButtonApplyItemStateChanged(evt);
            }
        });
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        jToggleButtonRun.setText("Connect");
        jToggleButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRunActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Launchpad-X / FL-Studio Gateway");

        jLabel4.setText("(C) 2020 Frederic Rible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(12, 12, 12))
        );

        jPanelKeyboard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelKeyboardKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelKeyboardKeyReleased(evt);
            }
        });

        jLabel5.setText("IN from LPX");

        jComboBox_LPX_in.setModel(new midiComboBoxModel(false));

        jLabel6.setText("OUT to LPX");

        jComboBox_LPX_out.setModel(new midiComboBoxModel(true));

        buttonGroupMode.add(jRadioButtonModeProg);
        jRadioButtonModeProg.setSelected(true);
        jRadioButtonModeProg.setText("Prog");
        jRadioButtonModeProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModeProgActionPerformed(evt);
            }
        });

        buttonGroupMode.add(jRadioButtonModeNative);
        jRadioButtonModeNative.setText("Native");
        jRadioButtonModeNative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonModeNativeActionPerformed(evt);
            }
        });

        jComboBox_FL_out_native.setModel(new midiComboBoxModel(true));

        jLabel7.setText("OUT to FL-Studio (Native)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelKeyboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jButtonApply)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_LPX_in, 0, 191, Short.MAX_VALUE)
                                .addComponent(jComboBox_LPX_out, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jToggleButtonRun)
                            .addGap(44, 44, 44)
                            .addComponent(jRadioButtonModeNative)
                            .addGap(10, 10, 10)
                            .addComponent(jRadioButtonModeProg))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_FL_in, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_FL_out, javax.swing.GroupLayout.Alignment.TRAILING, 0, 191, Short.MAX_VALUE)
                                .addComponent(jComboBox_FL_out_native, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_FL_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_FL_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_FL_out_native, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_LPX_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_LPX_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApply)
                    .addComponent(jToggleButtonRun)
                    .addComponent(jRadioButtonModeProg)
                    .addComponent(jRadioButtonModeNative))
                .addGap(24, 24, 24)
                .addComponent(jPanelKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        myMidi.stop();
        configure();
        if (jToggleButtonRun.isSelected())
            myMidi.start();
    }//GEN-LAST:event_jButtonApplyActionPerformed

    private void jToggleButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRunActionPerformed
        if (jToggleButtonRun.isSelected())
            myMidi.start();
        else
            myMidi.stop();
    }//GEN-LAST:event_jToggleButtonRunActionPerformed

    private void jPanelKeyboardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelKeyboardKeyPressed
        myMidi.pressPad(evt.getKeyCode(), 127);
    }//GEN-LAST:event_jPanelKeyboardKeyPressed

    private void jPanelKeyboardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelKeyboardKeyReleased
        myMidi.pressPad(evt.getKeyCode(), 0);
    }//GEN-LAST:event_jPanelKeyboardKeyReleased

    private void jButtonApplyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButtonApplyItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApplyItemStateChanged

    private void jRadioButtonModeProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModeProgActionPerformed
        myMidi.setMode(MidiHandler.eMode.Prog);
    }//GEN-LAST:event_jRadioButtonModeProgActionPerformed

    private void jRadioButtonModeNativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonModeNativeActionPerformed
        myMidi.setMode(MidiHandler.eMode.Native);
    }//GEN-LAST:event_jRadioButtonModeNativeActionPerformed

    private void configure() {
        myMidi.set((MidiDevice.Info) jComboBox_FL_in.getSelectedItem(),
                   (MidiDevice.Info) jComboBox_FL_out.getSelectedItem(),
                   (MidiDevice.Info) jComboBox_FL_out_native.getSelectedItem(),
                   (MidiDevice.Info) jComboBox_LPX_in.getSelectedItem(),
                   (MidiDevice.Info) jComboBox_LPX_out.getSelectedItem()
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MidiUnavailableException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMode;
    private javax.swing.JButton jButtonApply;
    private javax.swing.JComboBox<String> jComboBox_FL_in;
    private javax.swing.JComboBox<String> jComboBox_FL_out;
    private javax.swing.JComboBox<String> jComboBox_FL_out_native;
    private javax.swing.JComboBox<String> jComboBox_LPX_in;
    private javax.swing.JComboBox<String> jComboBox_LPX_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.f1oat.launchpad.x.gateway.jPanelKeyboard jPanelKeyboard;
    private javax.swing.JRadioButton jRadioButtonModeNative;
    private javax.swing.JRadioButton jRadioButtonModeProg;
    private javax.swing.JToggleButton jToggleButtonRun;
    // End of variables declaration//GEN-END:variables

    @Override
    public void udpateStatus() {
    }

    @Override
    public void notifyError() {
        this.jToggleButtonRun.setSelected(false);
        JOptionPane.showMessageDialog(new JFrame(), "MIDI error", "Dialog", JOptionPane.ERROR_MESSAGE);
    }
}
