/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.f1oat.launchpad.x.gateway;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testNothing() {
    }
}
